version: "3.9"

services:

  project-mh:
    image: alexeysubudaev/project-mh
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - project-mh
    restart: always
