version: "3.9"

services:

  db:
    image: postgres:14-alpine
    # environment:
    #   POSTGRES_DB: project-mh
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: 334
    # ports:
    #   - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_value:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: admin@admin.org
    #   PGADMIN_DEFAULT_PASSWORD: admin
    #   PGADMIN_CONFIG_SERVER_MODE: 'False'
    # ports:
    #   - "5050:80"
    env_file:
      - ./.env
    depends_on:
      - db

  project-mh:
    image: alexeysubudaev/project-mh
    restart: always
    depends_on:
      - db
      - pgadmin
    env_file:
      - ./.env

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project-mh
    restart: always

volumes:
  # static_value:
  # media_value:
  db_value:
