version: "3.9"

services:

  project-mh:
    image: alexeysubudaev/project-mh
    expose:
      - 8000
    restart: always

  # nginx:
  #   image: nginx:stable
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - project-mh
  #   restart: always
