version: "3.9"

services:

  project-mh:
    image: project-mh:latest
    build: .
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project-mh
    restart: always
